FACEBOOK_URL = "http://www.facebook.com/completefashionmagazine"
GPLUS_URL = "http://plus.google.com/completefashionmagazine"
TWITTER_URL = "http://twitter.com/completefashion"
PINTEREST =   "http://pinterest.com/completefashion"
TUMBLR =  "http://completefashion.tumblr.com/"